import { untrack } from "svelte";
import { SvelteMap } from "svelte/reactivity";

// Ids are generated by the store, so they are always numbers. Accepting strings
// too only made getItem("3") silently miss item 3.
export type ListItemId = number;

// What consumers see. Writes go through the store's methods: assigning `id` on a
// live proxy would make it disagree with its map key.
export type ListItem<T> = {
  readonly id: ListItemId;
  readonly data: Readonly<T>;
  readonly isSelected: boolean;
};

type MutableListItem<T> = { id: ListItemId; data: T; isSelected: boolean };

type ListItemPredicateFn<T> = (item: ListItem<T>) => boolean;

export type ListStore<T extends object> = ReturnType<
  typeof createListStore<T>
>;

/**
 * `T` must be a plain object (or array): `$state` only deep-proxies those, so fields
 * of class instances, Dates, Maps and so on would change without notifying anyone.
 */
export function createListStore<T extends object>() {
  let counter = 0;

  const list = new SvelteMap<ListItemId, MutableListItem<T>>();
  // Cached until an item is added or removed, instead of copied on every read.
  const items = $derived<ListItem<T>[]>([...list.values()]);

  /**
   * Stores a proxy over `data`. Don't keep mutating `data` afterwards: the proxy
   * copies each field on its first read, so later outside writes may or may not
   * show up, and never notify readers.
   */
  function addItem(data: T): ListItemId {
    const id = counter++;
    const item = $state({ id, data, isSelected: false });
    list.set(id, item);
    return id;
  }

  /** Returns false when there was no item with that id. */
  function removeItem(id: ListItemId): boolean {
    return list.delete(id);
  }

  // Lookups for writes are untracked, so calling a write method inside an effect
  // doesn't subscribe that effect to the item.
  function getMutable(id: ListItemId) {
    return untrack(() => list.get(id));
  }

  /** Returns false when there was no item with that id. */
  function setIsSelected(id: ListItemId, isSelected: boolean): boolean {
    const item = getMutable(id);
    if (!item) return false;
    item.isSelected = isSelected;
    return true;
  }

  /** Returns false when there was no item with that id. */
  function updateField<K extends keyof T>(
    id: ListItemId,
    field: K,
    value: T[K],
  ): boolean {
    const item = getMutable(id);
    if (!item) return false;
    untrack(() => item.data)[field] = value;
    return true;
  }

  /**
   * Call once (e.g. in a component's <script>) and read `.current` where needed;
   * each call builds a new filter.
   *
   * Every item gets its own membership derived, so a field change re-runs the
   * predicate for that item only. The list is only re-walked when an item joins or
   * leaves the result, or when items are added or removed, and the previous array
   * is kept when the members didn't change, so consumers don't re-run for nothing.
   */
  function derivedFilter(predicate: ListItemPredicateFn<T>) {
    type Entry = { item: ListItem<T>; readonly isMember: boolean };
    let entryById = new Map<ListItemId, Entry>();
    let previous: ListItem<T>[] = [];

    function createEntry(item: ListItem<T>): Entry {
      const isMember = $derived(predicate(item));
      return {
        item,
        get isMember() {
          return isMember;
        },
      };
    }

    // Re-runs only when items are added or removed. The membership deriveds must be
    // created here and read in `filtered`: Svelte never tracks a derived inside the
    // same reaction run that created it, so a single derived doing both would miss
    // updates to every item it had just added.
    const entries = $derived.by(() => {
      const next = new Map<ListItemId, Entry>();
      for (const [id, item] of list) {
        // Rebuilding the map drops the entries of removed items.
        next.set(id, entryById.get(id) ?? createEntry(item));
      }
      entryById = next;
      return [...next.values()];
    });

    const filtered = $derived.by(() => {
      const next = entries
        .filter((entry) => entry.isMember)
        .map((entry) => entry.item);

      const isUnchanged =
        next.length === previous.length &&
        next.every((item, i) => item === previous[i]);
      if (!isUnchanged) previous = next;
      return previous;
    });

    return {
      get current() {
        return filtered;
      },
    };
  }

  function getItem(id: ListItemId): ListItem<T> | null {
    return list.get(id) ?? null;
  }

  return {
    get state() {
      return items;
    },
    addItem,
    removeItem,
    updateField,
    derivedFilter,
    setIsSelected,
    getItem,
  };
}
